   SELECT B.YEAR, (B.MAXSIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
     FROM ECOLI_DATA AS A
     JOIN (
              SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
                FROM ECOLI_DATA
            GROUP BY YEAR(DIFFERENTIATION_DATE)
          ) AS B
      ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR, YEAR_DEV;