SELECT
SUM(GRADE.SCORE) AS SCORE,
EMP.EMP_NO,
EMP.EMP_NAME,
EMP.POSITION,
EMP.EMAIL

FROM HR_EMPLOYEES AS EMP
JOIN HR_GRADE AS GRADE ON EMP.EMP_NO = GRADE.EMP_NO

GROUP BY EMP.EMP_NO

ORDER BY SCORE DESC

LIMIT 1;